/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

import Dao.CourseDao;
import Dao.CourseDaoImpli;
import DbConnection.DbConnection;
import Model.Course;
import com.sun.jdi.connect.spi.Connection;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author aa014
 */
public class CourseFrame extends javax.swing.JFrame {
     CourseDao coursetDAO = new CourseDaoImpli();
    Integer deptId;
    String[] column = {"ID","Name"};
    DefaultTableModel defaultTableModel = null;
    public CourseFrame() {
      initComponents();
      this.setResizable(false);
      setLocationRelativeTo(null);
       fillCourseTable();
     //   this.pack();
    }
 private void fillCourseTable() {
        defaultTableModel = new DefaultTableModel(column,0);
        List<Course> department  = coursetDAO.getAllCourses();
        
        for(Course d:department ){
            Object[] row = {d.getId(),d.getName()};
            defaultTableModel.addRow(row);
            crsTable.setModel(defaultTableModel);
        }
         crsTable.getColumnModel().getColumn(0).setWidth(0);
        crsTable.getColumnModel().getColumn(0).setMinWidth(0);
    }
 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtiid = new javax.swing.JTextField();
        bntclear = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        crsTable = new javax.swing.JTable();
        bntadd = new javax.swing.JButton();
        crsback = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Course");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 180, -1));

        jPanel2.setBackground(new java.awt.Color(35, 47, 62));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Name: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        txtnam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtnam.setForeground(new java.awt.Color(255, 153, 0));
        txtnam.setToolTipText("Department Name");
        jPanel2.add(txtnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 110, 30));

        jLabel3.setBackground(new java.awt.Color(255, 153, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        txtiid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtiid.setForeground(new java.awt.Color(255, 153, 0));
        txtiid.setToolTipText("Department Name");
        jPanel2.add(txtiid, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 110, 30));

        bntclear.setBackground(new java.awt.Color(20, 110, 180));
        bntclear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntclear.setForeground(new java.awt.Color(255, 153, 0));
        bntclear.setText("CLEAR");
        bntclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntclearActionPerformed(evt);
            }
        });
        jPanel2.add(bntclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        btnupdate.setBackground(new java.awt.Color(20, 110, 180));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 153, 0));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        btndelete.setBackground(new java.awt.Color(20, 110, 180));
        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 153, 0));
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        crsTable.setBackground(new java.awt.Color(20, 110, 180));
        crsTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        crsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Code"
            }
        ));
        crsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(crsTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 120));

        bntadd.setBackground(new java.awt.Color(20, 110, 180));
        bntadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntadd.setForeground(new java.awt.Color(255, 153, 0));
        bntadd.setText("ADD");
        bntadd.setToolTipText("");
        bntadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntaddActionPerformed(evt);
            }
        });
        jPanel2.add(bntadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 580, 260));

        crsback.setBackground(new java.awt.Color(20, 110, 180));
        crsback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        crsback.setForeground(new java.awt.Color(255, 153, 0));
        crsback.setText("BACK");
        crsback.setToolTipText("");
        crsback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crsbackActionPerformed(evt);
            }
        });
        jPanel1.add(crsback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crsbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crsbackActionPerformed
this.hide();
HomeFrame homObj=new HomeFrame();
   homObj.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_crsbackActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(txtiid.getText());
   Course Obj=new Course();
  Obj.setId(id);
  coursetDAO.deleteCourse(Obj);
  fillCourseTable();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        
         int id=Integer.parseInt(txtiid.getText());
  String name=txtnam.getText();
   Course crs=new Course();
  crs.setId(id);
  crs.setName(name);
  coursetDAO.updateCourse(crs);
  fillCourseTable();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void bntclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntclearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_bntclearActionPerformed

    private void crsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crsTableMouseClicked
        // TODO add your handling code here:
        
         int index=crsTable.getSelectedRow();
        TableModel model=crsTable.getModel();
        String id=model.getValueAt(index, 0).toString();
        String name=model.getValueAt(index, 1).toString();
        txtiid.setText(id);
        txtnam.setText(name);
    }//GEN-LAST:event_crsTableMouseClicked

    private void bntaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntaddActionPerformed
      int id=Integer.parseInt(txtiid.getText());
  String name=txtnam.getText();
  Course crsObj=new Course();
  crsObj.setId(id);
  crsObj.setName(name);
  coursetDAO.addCourse(crsObj);
  fillCourseTable();
  clearFields();
         
        
// TODO add your handling code here:
    }//GEN-LAST:event_bntaddActionPerformed
private void clearFields(){
        txtiid.setText("");
        txtnam.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntadd;
    private javax.swing.JButton bntclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JTable crsTable;
    private javax.swing.JButton crsback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtiid;
    private javax.swing.JTextField txtnam;
    // End of variables declaration//GEN-END:variables

    private static class SQLException {

        public SQLException() {
        }
    }

    private static class PreparedStatement {

        public PreparedStatement() {
        }
    }
}
